/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysh.dev.codegen.ui;

import mysh.codegen.CodeUtil;
import mysh.util.UIs;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author hzzhangzhixian
 */
public class FieldGetSet extends javax.swing.JPanel {

    /**
     * Creates new form FieldGetSet
     */
    public FieldGetSet() {
        initComponents();
        
        classNameTxt.setLabel("ClassName");

        DocumentListener genTrigger = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                genCode();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                genCode();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                genCode();
            }
        };
        this.classNameTxt.getDocument().addDocumentListener(genTrigger);
        this.fieldDefineTxt.getDocument().addDocumentListener(genTrigger);
    }

    private void genCode() {
        this.codeGenTxt.setText(CodeUtil.genGetSetByFields(classNameTxt.getText(), fieldDefineTxt.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDefineTxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        codeGenTxt = new javax.swing.JTextArea();
        classNameTxt = new mysh.ui.JTextFieldWithTips();

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        fieldDefineTxt.setColumns(20);
        fieldDefineTxt.setRows(5);
        fieldDefineTxt.setText("\n    /**\n     * 商品编辑表id\n     */\n    @AnnonOfField(desc = \"商品编辑表id\", dbFieldName = \"edit_goods_id\", type = \"BIGINT\", primary = true)\n    private Long editGoodsId;");
        jScrollPane1.setViewportView(fieldDefineTxt);

        jSplitPane1.setTopComponent(jScrollPane1);

        codeGenTxt.setEditable(false);
        codeGenTxt.setColumns(20);
        codeGenTxt.setRows(5);
        codeGenTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeGenTxtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(codeGenTxt);

        jSplitPane1.setRightComponent(jScrollPane2);

        classNameTxt.setToolTipText("className");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addComponent(classNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codeGenTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeGenTxtMouseClicked
        UIs.copyToSystemClipboard(codeGenTxt.getText());
    }//GEN-LAST:event_codeGenTxtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mysh.ui.JTextFieldWithTips classNameTxt;
    private javax.swing.JTextArea codeGenTxt;
    private javax.swing.JTextArea fieldDefineTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
