
package mysh.dev.filesearch;

import mysh.util.UIUtil;

import javax.swing.*;
import java.awt.*;

/*
 * FileSearchFrame.java
 * Created on __DATE__, __TIME__
 */

/**
 * @author ZhangZhx
 */
public class FileSearchFrame extends javax.swing.JFrame implements FileSearch.ResultOutputPlugin {

	/**
	 * .
	 */
	private static final long serialVersionUID = -4971596194279352245L;

	/**
	 * Creates new form FileSearchFrame
	 */
	public FileSearchFrame() {

		initComponents();

		this.fileSearch = new FileSearch();
		this.fileSearch.setResultOutputPlugin(this);

	}

	public void appendResult(String msg) {
		SwingUtilities.invokeLater(
						() -> resultArea.append(msg + System.getProperty("line.separator"))
		);

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		fileDir = new javax.swing.JTextField();
		fileNamePattern = new javax.swing.JTextField();
		searchContent = new javax.swing.JTextField();
		startSearch = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		resultArea = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6587\u672c\u641c\u7d22");
		setLocationByPlatform(true);

		jLabel1.setText("关键字");

		jLabel2.setText("文件名");

		jLabel3.setText("搜索位置");

		fileNamePattern.setText(".*?\\.java");

		startSearch.setText("\u5f00\u59cb");
		startSearch.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(java.awt.event.ActionEvent evt) {

				startSearchActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(
														jLabel3).addComponent(jLabel1).addComponent(jLabel2)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
														fileNamePattern, javax.swing.GroupLayout.DEFAULT_SIZE, 284,
														Short.MAX_VALUE).addComponent(searchContent,
														javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE).addGroup(
														jPanel1Layout.createSequentialGroup().addComponent(fileDir,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 284,
																		Short.MAX_VALUE).addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))).addGap(
										14, 14, 14).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														false).addComponent(startSearch,
														javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
														jLabel1).addComponent(searchContent,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
														jLabel2).addComponent(fileNamePattern,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(
														jLabel3).addComponent(startSearch).addComponent(fileDir,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));

		getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("\u7ed3\u679c"));

		resultArea.setColumns(20);
		resultArea.setEditable(false);
		resultArea.setRows(5);
		jScrollPane1.setViewportView(resultArea);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE));

		getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	// GEN-END:initComponents

	private void startSearchActionPerformed(java.awt.event.ActionEvent evt) {

		if (this.startSearch.getText().equals("开始")) {
			this.startSearch.setText("结束");

			new Thread(new Runnable() {

				@Override
				public void run() {

					FileSearchFrame.this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

					try {
						FileSearchFrame.this.resultArea.setText("");
						FileSearchFrame.this.fileSearch.setFileDir(FileSearchFrame.this.fileDir.getText());
						FileSearchFrame.this.fileSearch.setFileNameFilterPattern(FileSearchFrame.this.fileNamePattern.getText());
						FileSearchFrame.this.fileSearch.setSearchContent(FileSearchFrame.this.searchContent.getText());
						FileSearchFrame.this.fileSearch.startSearching();
					} catch (Exception e) {
						e.printStackTrace();
						JOptionPane.showMessageDialog(FileSearchFrame.this, e.toString(), "出错了",
										JOptionPane.ERROR_MESSAGE);
					} finally {
						FileSearchFrame.this.setCursor(Cursor.getDefaultCursor());
						FileSearchFrame.this.startSearch.setText("开始");
					}

					FileSearchFrame.this.setCursor(Cursor.getDefaultCursor());
				}
			}).start();
		} else {
			this.fileSearch.stopSearching();
			FileSearchFrame.this.setCursor(Cursor.getDefaultCursor());
			this.startSearch.setText("开始");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		UIUtil.useNimbusLookAndFeel();
		UIUtil.resetFont(null);

		java.awt.EventQueue.invokeLater(() -> {

			FileSearchFrame frame = new FileSearchFrame();
			frame.setLocationRelativeTo(null);
			frame.setVisible(true);
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify

	private javax.swing.JTextField fileDir;

	private javax.swing.JTextField fileNamePattern;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JPanel jPanel2;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTextArea resultArea;

	private javax.swing.JTextField searchContent;

	private javax.swing.JButton startSearch;

	// End of variables declaration//GEN-END:variables

	private FileSearch fileSearch;
}
