package mysh.cluster;

/**
 * @author Mysh
 * @since 14-1-30 下午6:36
 */
public interface IClusterService {

	/**
	 * run task of user within timeout(milli-second).
	 *
	 * @param timeout        execution time(milli-second), non-positive value represent for never timeout.
	 * @param subTaskTimeout execution time(milli-second) of each subTask(generated by cUser.fork()),
	 *                       which will be passed to cUser.procSubTask()
	 * @throws ClusterExp.NotMaster
	 * @throws ClusterExp.NoWorkers
	 * @throws InterruptedException
	 * @throws ClusterExp.TaskTimeout
	 */
	<T, ST, SR, R> R runTask(IClusterUser<T, ST, SR, R> cUser, T task, int timeout, int subTaskTimeout)
					throws ClusterExp, InterruptedException;

}
