package mysh.cluster;

/**
 * @author Mysh
 * @since 14-1-30 下午6:36
 */
public interface IClusterService {

	/**
	 * run task of user within timeout(milli-second).
	 *
	 * @param timeout        execution time(milli-second), non-positive value represent for never timeout.
	 * @param subTaskTimeout execution time(milli-second) of each subTask(generated by cUser.fork()),
	 *                       which will be passed to cUser.procSubTask()
	 * @throws mysh.cluster.ClusterExp        exceptions from cluster, generally about cluster
	 *                                        status and task status.
	 * @throws java.lang.InterruptedException current thread interrupted.
	 * @throws java.lang.Exception            other exceptions.
	 */
	<T, ST, SR, R> R runTask(IClusterUser<T, ST, SR, R> cUser, T task, int timeout, int subTaskTimeout)
					throws Exception;

}
