package mysh.cluster;

/**
 * @author Mysh
 * @since 14-1-30 下午6:36
 */
public interface IClusterService {

	/**
	 * run task of user within timeout(milli-second).
	 * WARNING: check {@link mysh.cluster.rpc.thrift.RpcUtil#wrapSyncClient} when update signature.
	 *
	 * @param namespace      execute within this namespace. it's used for resource access control.
	 * @param timeout        execution time(milli-second), non-positive value represent for never timeout.
	 * @param subTaskTimeout execution time(milli-second) of each subTask(generated by cUser.fork()),
	 *                       which will be passed to cUser.procSubTask()
	 * @return execution result.
	 * @throws mysh.cluster.ClusterExp        exceptions from cluster, generally about cluster
	 *                                        status and task status.
	 * @throws java.lang.InterruptedException current thread interrupted.
	 * @throws java.lang.Throwable            other exceptions.
	 */
	<T, ST, SR, R> R runTask(String namespace, IClusterUser<T, ST, SR, R> cUser, T task, int timeout,
	                         int subTaskTimeout) throws Throwable;

}
