package mysh.cluster;

import java.rmi.Remote;
import java.rmi.RemoteException;

/**
 * @author Mysh
 * @since 14-1-30 下午6:36
 */
interface IClusterService extends Remote {

	/**
	 * run task of user within timeout(milli-second).
	 *
	 * @param timeout        execution time(milli-second), non-positive value represent for never timeout.
	 * @param subTaskTimeout execution time(milli-second) of each subTask(generated by cUser.fork()),
	 *                       which will be passed to cUser.procSubTask()
	 * @throws mysh.cluster.ClusterExcp.NotMaster
	 * @throws mysh.cluster.ClusterExcp.NoWorkers
	 * @throws java.rmi.RemoteException
	 * @throws InterruptedException
	 * @throws mysh.cluster.ClusterExcp.TaskTimeout
	 */
	<T, ST, SR, R> R runTask(IClusterUser<T, ST, SR, R> cUser, T task, int timeout, int subTaskTimeout)
					throws RemoteException,
					ClusterExcp.NotMaster, ClusterExcp.NoWorkers, ClusterExcp.TaskTimeout,
					InterruptedException;
}
