package mysh.cluster;

import java.rmi.Remote;
import java.rmi.RemoteException;

/**
 * @author Mysh
 * @since 14-1-30 下午6:36
 */
public interface IClusterService extends Remote {
	/**
	 * run task of user within timeout(milli-second).
	 *
	 * @param timeout        execution time(milli-second), non-positive value represent for never timeout.
	 * @param subTaskTimeout execution time(milli-second) of each subTask(generated by cUser.fork()),
	 *                       which will be passed to cUser.procSubTask()
	 */
	<R> R runTask(IClusterUser<R> cUser, Object task, int timeout, int subTaskTimeout)
					throws RemoteException,
					ClusterExcp.NotMaster, ClusterExcp.NoWorkers, ClusterExcp.TaskTimeout,
					InterruptedException;
}
