/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mysh.dev.clj.interpreter;

import mysh.util.UIs;

import javax.swing.*;
import java.awt.*;

/**
 * @author Allen
 */
public class CLJInterpreterFrame extends javax.swing.JFrame {

	private final CLJInterpreterMain cljPanel;

	/**
	 * Creates new form CLJInterpreterFrame
	 */
	public CLJInterpreterFrame(JFrame outerFrame) {
		initComponents();
		this.getContentPane().setLayout(new BorderLayout());
		cljPanel = new CLJInterpreterMain(outerFrame != null ? outerFrame : this);
		this.getContentPane().add(cljPanel, BorderLayout.CENTER);

		this.setLocationRelativeTo(null);

		this.setIconImage(Toolkit.getDefaultToolkit().getImage(
						this.getClass().getClassLoader().getResource("mysh/dev/clj/interpreter/clojure.png")));
	}

	public void startCljThread() {
		cljPanel.startCljThread();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Clojure Interpreter (Esc, F1, Ctrl+Enter, Alt+Left/Right)");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGap(0, 474, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGap(0, 565, Short.MAX_VALUE)
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
	      /*
	       * Set the Nimbus look and feel
         */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	      /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CLJInterpreterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CLJInterpreterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CLJInterpreterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CLJInterpreterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		UIs.resetFont(null);
        /*
         * Create and display the form
         */
		EventQueue.invokeLater(new Runnable() {

			public void run() {
				CLJInterpreterFrame frame = new CLJInterpreterFrame(null);
				frame.setVisible(true);
				frame.startCljThread();
			}
		});
	}
	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
