/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mysh.dev.clj.interpreter;

import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

import javax.swing.text.DefaultCaret;

/**
 *
 * @author Allen
 */
public class CLJTextPanel extends javax.swing.JPanel {

    /**
     * Creates new form CLJTextPanel
     */
    public CLJTextPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        scroll = new RTextScrollPane(this.text, true);

        text.setColumns(20);
        text.setLineWrap(true);
        text.setRows(1);
        text.setTabSize(1);
        text.setCodeFoldingEnabled(true);
        text.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        text.setMarkOccurrences(true);
        text.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_CLOJURE);
        text.setLineWrap(true);
        ((DefaultCaret)text.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        setLayout(new java.awt.BorderLayout());

        scroll.setAutoscrolls(true);
        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JScrollPane scroll;
    org.fife.ui.rsyntaxtextarea.RSyntaxTextArea text;
    // End of variables declaration//GEN-END:variables
}
